# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epo1jzhRlNfqMRq3zfO0s7KV06jcNme3
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np
import requests

st.set_page_config(layout="wide")

# =====================================================
# STYLE
# =====================================================
st.markdown("""
<style>
[data-testid="stAppViewContainer"] { background-color: #1c6f9c; }
[data-testid="stSidebar"] { background-color: #174f73; }
[data-testid="stSidebar"] * { color: white !important; }

.header { text-align:center; color:white; margin-bottom:10px; font-size:30px }
.section-title { text-align:center; color:white; margin:10px 0; font-size:18px; }

.card {
    background:white;
    border-radius:8px;
    padding:10px;
    margin-bottom:15px;
}

.table-box {
    background:#f5fbff;
    padding:5px;
    border-radius:6px;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="header">
<h2>GRAND VALLEY STATE UNIVERSITY</h2>
</div>
""", unsafe_allow_html=True)

# =====================================================
# LOAD DATA
# =====================================================
@st.cache_data
def load_data():
    df = pd.read_csv("gvsudegree_clean.csv")

    df['Graduated'] = pd.to_numeric(df['Graduated'], errors='coerce').fillna(0)

    df['stfip'] = pd.to_numeric(df['stfip'], errors='coerce')
    df['stfip'] = df['stfip'].fillna(0)
    df['stfip'] = df['stfip'].astype(int).astype(str).str.zfill(2)

    df['fips'] = pd.to_numeric(df['fips'], errors='coerce') \
        .fillna(0).astype(int).astype(str).str.zfill(5)

    return df

df = load_data()

# =====================================================
# STATE MAP
# =====================================================
fips_to_state = {
    "00":"Out of US","01":"Alabama","02":"Alaska","04":"Arizona","05":"Arkansas",
    "06":"California","08":"Colorado","09":"Connecticut","10":"Delaware",
    "11":"DC","12":"Florida","13":"Georgia","15":"Hawaii","16":"Idaho",
    "17":"Illinois","18":"Indiana","19":"Iowa","20":"Kansas","21":"Kentucky",
    "22":"Louisiana","23":"Maine","24":"Maryland","25":"Massachusetts",
    "26":"Michigan","27":"Minnesota","28":"Mississippi","29":"Missouri",
    "30":"Montana","31":"Nebraska","32":"Nevada","33":"New Hampshire",
    "34":"New Jersey","35":"New Mexico","36":"New York","37":"North Carolina",
    "38":"North Dakota","39":"Ohio","40":"Oklahoma","41":"Oregon",
    "42":"Pennsylvania","44":"Rhode Island","45":"South Carolina",
    "46":"South Dakota","47":"Tennessee","48":"Texas","49":"Utah",
    "50":"Vermont","51":"Virginia","53":"Washington","54":"West Virginia",
    "55":"Wisconsin","56":"Wyoming"
}

# =====================================================
# SIDEBAR
# =====================================================
section = st.sidebar.radio(
    "Table of Contents",
    ["National","Michigan","State Table","County Table", "Industry Analysis", "Employer Analysis"]
)

if section == "National":

    # -------------------------
    # TITLE + SOURCE
    # -------------------------
    st.markdown(
        "<h3 style='text-align:center;color:white; font-size:30'>Alumni Location by State</h3>",
        unsafe_allow_html=True
    )

    st.markdown(
        "<p style='text-align:center;color:white;font-size:18px;'>Source: GVSU Institutional Analysis</p>",
        unsafe_allow_html=True
    )

    state_df = df.groupby(['state','stfip'], as_index=False)['Graduated'].sum()
    state_df['State Name'] = state_df['stfip'].map(fips_to_state)

    us_states = state_df[state_df['stfip'] != "00"].copy()

    # -------------------------
    # ENSURE NUMERIC
    # -------------------------
    us_states['Graduated'] = pd.to_numeric(us_states['Graduated'], errors='coerce')

    # -------------------------
    # BIN FUNCTION (FINAL)
    # -------------------------
    def assign_bin(x):
        if x >= 5000: return "5000–136816"
        elif x >= 1000: return "1000–5000"
        elif x >= 567: return "567–1000"
        elif x >= 323: return "323–567"
        elif x >= 203: return "203–323"
        elif x >= 118: return "118–203"
        elif x >= 84: return "84–118"
        elif x >= 60: return "60–84"
        elif x >= 33: return "33–60"
        else: return "6–33"

    us_states['bin'] = us_states['Graduated'].apply(assign_bin)

    # -------------------------
    # ORDER (CRITICAL)
    # -------------------------
    bin_order = [
        "5000–136816",
        "1000–5000",
        "567–1000",
        "323–567",
        "203–323",
        "118–203",
        "84–118",
        "60–84",
        "33–60",
        "6–33"
    ]

    # -------------------------
    # COLORS (DARK → LIGHT)
    # -------------------------
    colors = [
        "#08306B",  # very dark
        "#08519C",
        "#2171B5",
        "#4292C6",
        "#6BAED6",
        "#9ECAE1",
        "#C6DBEF",
        "#DEEBF7",
        "#F7FBFF",
        "#FFFFFF"   # lightest
    ]

    # -------------------------
    # MAP
    # -------------------------
    fig = px.choropleth(
        us_states,
        locations='state',
        locationmode='USA-states',
        color='bin',
        scope='usa',
        category_orders={"bin": bin_order},
        color_discrete_sequence=colors
    )

    # -------------------------
    # HOVER (CLEAN)
    # -------------------------
    fig.update_traces(
        customdata=us_states[['State Name','Graduated']],
        hovertemplate="<b>%{customdata[0]}</b><br>%{customdata[1]:,}<extra></extra>"
    )

    # -------------------------
    # OUT-OF-US BUBBLE (FLORIDA AREA)
    # -------------------------
    out_us_df = df[(df['stfip'] == "00") | (df['stfip'].isna())]

    out_us_total = out_us_df['Graduated'].sum()
    out_us_count = len(out_us_df)

    fig.add_scattergeo(
        lon=[-78],   # near Florida
        lat=[24],
        text=[f"Out of US<br>{int(out_us_total):,}<br>Obs: {out_us_count}"],
        mode='markers+text',
        marker=dict(size=50, color='red'),
        textposition="top center",
        showlegend=False
    )

    # -------------------------
    # LAYOUT
    # -------------------------
    fig.update_layout(
        height=750,
        dragmode=False,
        margin=dict(l=0, r=0, t=20, b=0),
        legend_title_text="Graduates (Binned)"
    )

    fig.update_geos(scope="usa", visible=False)

    # -------------------------
    # DISPLAY
    # -------------------------
    st.plotly_chart(fig, use_container_width=True)

    # =====================================================
    # TABLE
    # =====================================================
    st.markdown('<div class="section-title">State Table</div>', unsafe_allow_html=True)

    table = state_df.copy()

    table = table.rename(columns={
        'stfip': 'StateFip',
        'State Name': 'State'
    })

    table = table[['StateFip','State','Graduated']]

    total = table['Graduated'].sum()
    table['Share of Total'] = (table['Graduated']/total*100).round(2)

    table = table.sort_values('Graduated', ascending=False)

    st.dataframe(table, use_container_width=True)

# =====================================================
# MICHIGAN DISTRIBUTION (FINAL)
# =====================================================
if section == "Michigan":

    # -------------------------
    # TITLE + SOURCE
    # -------------------------
    st.markdown(
        "<h3 style='text-align:center;color:white; font-size:30'>Alumni Location by County</h3>",
        unsafe_allow_html=True
    )

    st.markdown(
        "<p style='text-align:center;color:white;font-size:18px;'>Source: GVSU Institutional Analysis</p>",
        unsafe_allow_html=True
    )

    # -------------------------
    # MAJOR FILTER
    # -------------------------
    majors = ['All'] + sorted(df['Major'].dropna().unique())
    selected_major = st.selectbox("Select Major", majors)

    # -------------------------
    # FILTER DATA
    # -------------------------
    if selected_major == "All":
        dff = df[df['stfip'] == "26"].copy()
    else:
        dff = df[(df['stfip'] == "26") & (df['Major'] == selected_major)].copy()

    # -------------------------
    # LOAD GEOJSON
    # -------------------------
    geo = requests.get(
        "https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json"
    ).json()

    features = [f for f in geo["features"] if f["id"].startswith("26")]

    county_lookup = pd.DataFrame({
        "fips": [f["id"] for f in features],
        "County": [f["properties"]["NAME"] for f in features]
    })

    # -------------------------
    # AGGREGATE
    # -------------------------
    county_df = dff.groupby('fips', as_index=False)['Graduated'].sum()

    merged = county_lookup.merge(county_df, on='fips', how='left')
    merged['Graduated'] = merged['Graduated'].fillna(0)

    # -------------------------
    # LOG + CLIP (FOR VISUAL BALANCE)
    # -------------------------
    merged['log'] = np.log1p(merged['Graduated'])

    lower = merged['log'].quantile(0.05)
    upper = merged['log'].quantile(0.95)

    merged['log_clipped'] = merged['log'].clip(lower, upper)

    # -------------------------
    # MAP
    # -------------------------
    fig = px.choropleth(
        merged,
        geojson={"type": "FeatureCollection", "features": features},
        locations='fips',
        color='log_clipped',
        color_continuous_scale='Blues',
        range_color=(lower, upper)
    )

    fig.update_traces(
        customdata=merged[['County', 'Graduated']],
        hovertemplate="<b>%{customdata[0]}</b><br>%{customdata[1]:,}<extra></extra>"
    )

    fig.update_geos(fitbounds="locations", visible=False)

    fig.update_layout(
        height=700,
        dragmode=False,
        margin=dict(l=0, r=0, t=20, b=0)
    )

    st.plotly_chart(fig, use_container_width=True)

    # -------------------------
    # TABLE
    # -------------------------
    table = merged[['County', 'Graduated']].copy()

    total = table['Graduated'].sum()

    if total > 0:
        table['Share of Total'] = (table['Graduated'] / total * 100).round(2)
    else:
        table['Share of Total'] = 0

    table = table.sort_values('Graduated', ascending=False)

    st.dataframe(table, use_container_width=True)

# =====================================================
# STATE TABLE
# =====================================================
if section == "State Table":
    # -------------------------
    # TITLE + SOURCE
    # -------------------------
    st.markdown(
        "<h3 style='text-align:center;color:white; font-size:30'>Alumni Location by State</h3>",
        unsafe_allow_html=True
    )

    st.markdown(
        "<p style='text-align:center;color:white;font-size:18px;'>Source: GVSU Institutional Analysis</p>",
        unsafe_allow_html=True
    )

    majors = ['All'] + sorted(df['Major'].dropna().unique())
    selected_major = st.selectbox("Major", majors)

    dff = df if selected_major=="All" else df[df['Major']==selected_major]

    table = dff.groupby('stfip', as_index=False)['Graduated'].sum()
    table['State'] = table['stfip'].map(fips_to_state)

    total = table['Graduated'].sum()
    table['Share of Total'] = (table['Graduated']/total*100).round(2)

    table = table.rename(columns={'stfip':'StateFip'})
    table = table[['StateFip','State','Graduated','Share of Total']]

    table = table.sort_values('Graduated', ascending=False)
    st.dataframe(table, use_container_width=True)

# =====================================================
# COUNTY TABLE
# =====================================================
if section == "County Table":

    # -------------------------
    # TITLE + SOURCE
    # -------------------------
    st.markdown(
        "<h3 style='text-align:center;color:white; font-size:30'>Alumni Location by County</h3>",
        unsafe_allow_html=True
    )

    st.markdown(
        "<p style='text-align:center;color:white;font-size:18px;'>Source: GVSU Institutional Analysis</p>",
        unsafe_allow_html=True
    )

    states = sorted(df['stfip'].map(fips_to_state).dropna().unique())
    selected_state = st.selectbox("State", states)

    majors = ['All'] + sorted(df['Major'].dropna().unique())
    selected_major = st.selectbox("Major", majors)

    stfip_val = {v:k for k,v in fips_to_state.items()}[selected_state]

    geo = requests.get("https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json").json()

    lookup = pd.DataFrame({
        "fips":[f["id"] for f in geo["features"]],
        "County":[f["properties"]["NAME"] for f in geo["features"]]
    })

    lookup = lookup[lookup['fips'].str.startswith(stfip_val)]

    dff = df if selected_major=="All" else df[df['Major']==selected_major]
    dff = dff[dff['stfip']==stfip_val]

    agg = dff.groupby('fips',as_index=False)['Graduated'].sum()

    table = lookup.merge(agg,on='fips',how='left')
    table['Graduated']=table['Graduated'].fillna(0)

    total = table['Graduated'].sum()
    table['Share of Total'] = (table['Graduated']/total*100).round(2)

    table = table.sort_values('Graduated', ascending=False)

    st.dataframe(table, use_container_width=True)

# =====================================================
# INDUSTRY ANALYSIS (FINAL)
# =====================================================
if section == "Industry Analysis":
    # -------------------------
    # TITLE + SOURCE
    # -------------------------
    st.markdown(
        "<h3 style='text-align:center;color:white; font-size:30'>Industry Analysis</h3>",
        unsafe_allow_html=True
    )

    st.markdown(
        "<p style='text-align:center;color:white;font-size:18px;'>Source: GrayDI</p>",
        unsafe_allow_html=True
    )

    

    FILE_PATH = "graydi_fips_mapv.xlsx"

    df_ind = pd.read_excel(FILE_PATH, sheet_name="Company Industry")

    # Remove totals
    df_ind = df_ind[~df_ind["Industries"].str.contains("Total", case=False, na=False)]

    TOP = st.number_input("Top Industries", 1, 50, 10)

    df_ind = df_ind.sort_values("Count of Company Industry", ascending=False).head(TOP)

    total = df_ind["Count of Company Industry"].sum()
    df_ind["Percent"] = df_ind["Count of Company Industry"] / total
    df_ind["log"] = np.log1p(df_ind["Count of Company Industry"])

    # =====================================================
    # LAYOUT
    # =====================================================
    col1, col2 = st.columns(2)

    # BAR
    with col1:
        fig_bar = px.bar(
            df_ind,
            x="Count of Company Industry",
            y="Industries",
            orientation="h",
            text="Count of Company Industry"
        )
        fig_bar.update_yaxes(autorange="reversed")
        st.plotly_chart(fig_bar, use_container_width=True)

    # TREEMAP (LOG SCALE + CLEAN HOVER)
    with col2:
        fig_tree = px.treemap(
            df_ind,
            path=["Industries"],
            values="Count of Company Industry",
            color="log",
            color_continuous_scale="Blues"
        )

        fig_tree.update_traces(
            customdata=df_ind[['Percent']],
            hovertemplate="<b>%{label}</b><br>%{customdata[0]:.2%}<extra></extra>"
        )

        st.plotly_chart(fig_tree, use_container_width=True)

# =====================================================
# EMPLOYER ANALYSIS (FINAL)
# =====================================================
if section == "Employer Analysis":
    # -------------------------
    # TITLE + SOURCE
    # -------------------------
    st.markdown(
        "<h3 style='text-align:center;color:white; font-size:30'>Employer Analysis</h3>",
        unsafe_allow_html=True
    )

    st.markdown(
        "<p style='text-align:center;color:white;font-size:18px;'>Source: GrayDI</p>",
        unsafe_allow_html=True
    )

    

    FILE_PATH = "graydi_fips_mapv.xlsx"
    xls = pd.ExcelFile(FILE_PATH)

    exclude = ["Data","Company Industry","Employers Total", "Dynamic Table", "Majors", "Sheet22"]
    sheets = [s for s in xls.sheet_names if s not in exclude]

    col1, col2 = st.columns([2,1])

    with col1:
        industry = st.selectbox("Industry", sheets)
    with col2:
        TOP = st.number_input("Top N Employers", 1, 100, 10)

    df_emp = pd.read_excel(FILE_PATH, sheet_name=industry)

    name_col = df_emp.columns[0]
    value_col = df_emp.select_dtypes(include=np.number).columns[0]

    df_emp = df_emp[[name_col, value_col]].dropna()

    # 🔥 REMOVE TOTAL ROWS (IMPORTANT FIX)
    df_emp = df_emp[~df_emp[name_col].str.contains("Total", case=False, na=False)]

    df_emp = df_emp.sort_values(value_col, ascending=False).head(TOP)

    total = df_emp[value_col].sum()
    df_emp["Percent"] = df_emp[value_col] / total
    df_emp["log"] = np.log1p(df_emp[value_col])

    # =====================================================
    # LAYOUT
    # =====================================================
    col1, col2 = st.columns(2)

    # BAR
    with col1:
        fig_bar = px.bar(
            df_emp,
            x=value_col,
            y=name_col,
            orientation="h",
            text=value_col
        )
        fig_bar.update_yaxes(autorange="reversed")
        st.plotly_chart(fig_bar, use_container_width=True)

    # TREEMAP
    with col2:
        fig_tree = px.treemap(
            df_emp,
            path=[name_col],
            values=value_col,
            color="log",
            color_continuous_scale="Blues"
        )

        fig_tree.update_traces(
            customdata=df_emp[['Percent']],
            hovertemplate="<b>%{label}</b><br>%{customdata[0]:.2%}<extra></extra>"
        )

        st.plotly_chart(fig_tree, use_container_width=True)

    
